
---
- name: 'настройка доступности созданного пользователя только с "С"'
  ansible.builtin.lineinfile:
    path: "{{ path }}"
    line: "host   {{ item }}             developer          192.168.25.134/32                      password"
  with_items:
    - myapp
    - myauth
  notify: restart psql
