
---
#- name: 'Отключить на "В" авторизацию по паролю'
#  hosts: B
#  become: yes

#  roles:
#    - example1

#- name: 'На "В" добавить пользователя DevOps, настроить авторизацию по ключам и предоставить ему доступ "sudo" без пароля. Установка на "В" postgresql и его конифгурирование'
#  hosts: B
#  become: yes

#  roles:
#    - example2
#    - example3_1

- name: 'Создание БД myapp и myauth и пользователя developer. Настройка доступа к developer только с "С"'
  hosts: B
  become: yes

  roles:
    - example3_2
    - example4

- name: 'Проверка доступности БД с "С"'
  hosts: C
  become: yes

  roles:
    - example5
