
---
- name: 'создание БД myapp и myauth'
  community.postgresql.postgresql_db:
    name: "{{ item }}"
  with_items:
    - myapp
    - myauth


- name: 'создание роли developer'
  community.postgresql.postgresql_user:
    name: developer

- name: 'права на подключение к myauth'
  community.postgresql.postgresql_privs:
    database: myauth
    state: present
    privs: CONNECT
    type: database
    roles: developer


- name: 'права на чтение таблиц в myauth'
  community.postgresql.postgresql_privs:
    database: myauth
    state: present
    privs: SELECT
    objs: ALL_IN_SCHEMA
    schema: public
    roles: developer


- name: 'запрет на создание таблиц в myauth'
  community.postgresql.postgresql_privs:
    database: myauth
    state: absent
    privs: CREATE
    type: schema
    obj: public
    roles: public



