
---
- name: 'создание БД myapp и myauth'
  community.postgresql.postgresql_db:
    name: "{{ item }}"
  with_items:
    - myapp
    - myauth

- name: 'создание роли developer'
  community.postgresql.postgresql_user:
    name: developer
    password: '123'


