
---
- name: create db myapp
  community.postgresql.postgresql_db:
    name: "{{ item }}"
  with_items:
    - myapp
    - myauth

- name: create user developer
  community.postgresql.postgresql_user:
    db: myapp
    name: developer
    password: '123'
    priv: "CONNECT"


