
---

- name: install psql
  apt:
    name: ['postgresql','python3-psycopg2']
    state: latest

- name: change postgresql.conf
  ansible.builtin.lineinfile:
    path: /etc/postgresql/14/main/postgresql.conf
    regexp: "#listen_addresses = 'localhost'"
    line: "listen_addresses = '*'"
  notify: restart psql

- name: change pg_hba
  ansible.builtin.lineinfile:
    path: /etc/postgresql/14/main/pg_hba.conf
    regexp: "local   all             postgres                                peer"
    line: "local   all             postgres                                trust"
  notify: restart psql

- name: change pg_hba2
  ansible.builtin.lineinfile:
    path: /etc/postgresql/14/main/pg_hba.conf
    line: "host    all             all              192.168.25.132/32       trust"
  notify: restart psql

- name: create db myapp
  community.postgresql.postgresql_db:
    name: "{{ item }}"
  with_items:
    - myapp
    - myauth

