
---

- name: 'установка psql на "В"'
  apt:
    name: ['postgresql','python3-psycopg2']
    state: latest

- name: 'изменение в postgresql.conf'
  ansible.builtin.lineinfile:
    path: /etc/postgresql/14/main/postgresql.conf
    regexp: "#listen_addresses = 'localhost'"
    line: "listen_addresses = '*'"
  notify: restart psql

- name: 'изменение в pg_hba.conf'
  ansible.builtin.lineinfile:
    path: /etc/postgresql/14/main/pg_hba.conf
    regexp: "local   all             postgres                                peer"
    line: "local   all             postgres                                trust"
  notify: restart psql


