
---
- name: 'создание пользователя DevOps на "В"'
  user:
    name: "{{ user }}"
    group: sudo
    shell: /bin/bash
    password: '$6$B.AxpK8zHtpXIZPP$kStM3EB2ncV0JqDWeI46HGOD4HkBirMdWbLnV6qEwp/p/ZxqsmpafCBcXI825pTTwx4mwQokPXW7QTPy2poXk1'
    generate_ssh_key: yes


- name: 'копирование нашего ключа пользовтелю DevOps на "В"'
  ansible.posix.authorized_key:
    user: "{{ user }}"
    state: present
    key: "{{ lookup('file', '/home/god/.ssh/id_rsa.pub') }}"

- name: 'делаем sudo без пароля пользователю DevOps'
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    line: '"{{ user }}" ALL=(ALL) NOPASSWD:ALL'
